version: '2'
services:
  shuoj_frontend:
    build:
      context: .
      args:
        - BASE_URL=http://172.20.10.2:8081
        - PORT=8080
    container_name: shuoj_frontend
    ports:
      - '8080:8080'
